part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const home = _Paths.home;
  static const courses = _Paths.courses;
  static const profile = _Paths.profile;
  static const customBottomNav = _Paths.customBottomNav;
  static const splashScreen = _Paths.splashScreen;
  static const logIn = _Paths.logIn;
  static const registration = _Paths.registration;
  static const registrationOtp = _Paths.registrationOtp;
  static const recoveryOtp = _Paths.recoveryOtp;
  static const createNewPassword = _Paths.createNewPassword;
  static const recoveryPassword = _Paths.recoveryPassword;
  static const onboarding = _Paths.onboarding;
  static const news = _Paths.news;
  static const courseDetails = _Paths.courseDetails;
  static const classDetails = _Paths.classDetails;
  static const newsDetails = _Paths.newsDetails;
  static const notifications = _Paths.notifications;
  static const checkout = _Paths.checkout;
  static const bookingConfirmed = _Paths.bookingConfirmed;
  static const instructorDetails = _Paths.instructorDetails;
  static const courseInstructorDetails = _Paths.courseInstructorDetails;
  static const myBookings = _Paths.myBookings;
  static const bookingDetails = _Paths.bookingDetails;
  static const topUpSuccess = _Paths.topUpSuccess;
  static const productDetails = _Paths.productDetails;
  static const aboutUs = _Paths.aboutUs;
  static const editProfile = _Paths.editProfile;
  static const memberships = _Paths.memberships;
  static const membershipDetails = _Paths.membershipDetails;
  static const termsConditions = _Paths.termsConditions;
  static const wallet = _Paths.wallet;
  static const orderHistory = _Paths.orderHistory;
  static const filter = _Paths.filter;
  static const errorScreen = _Paths.errorScreen;
  static const notFoundScreen = _Paths.notFoundScreen;
  static const privacyPolicy = _Paths.privacyPolicy;
  static const faq = _Paths.faq;
}

abstract class _Paths {
  _Paths._();
  static const home = '/home';
  static const courses = '/courses';
  static const profile = '/profile';
  static const customBottomNav = '/custom-bottom-nav';
  static const splashScreen = '/splash-screen';
  static const logIn = '/log-in';
  static const registration = '/registration';
  static const registrationOtp = '/registration-otp';
  static const recoveryOtp = '/recovery-otp';
  static const createNewPassword = '/create-new-password';
  static const recoveryPassword = '/recovery-password';
  static const onboarding = '/onboarding';
  static const news = '/news';
  static const courseDetails = '/course-details';
  static const classDetails = '/class-details';
  static const newsDetails = '/news-details';
  static const notifications = '/notifications';
  static const checkout = '/checkout';
  static const bookingConfirmed = '/booking-confirmed';
  static const instructorDetails = '/instructor-details';
  static const courseInstructorDetails = '/course-instructor-details';
  static const myBookings = '/my-bookings';
  static const bookingDetails = '/booking-details';
  static const topUpSuccess = '/top-up-success';
  static const productDetails = '/product-details';
  static const aboutUs = '/about-us';
  static const editProfile = '/edit-profile';
  static const memberships = '/memberships';
  static const membershipDetails = '/membership-details';
  static const termsConditions = '/terms-conditions';
  static const wallet = '/wallet';
  static const orderHistory = '/order-history';
  static const filter = '/filter';
  static const errorScreen = '/error-screen';
  static const notFoundScreen = '/not-found-screen';
  static const privacyPolicy = '/privacy-policy';
  static const faq = '/faq';
}
